name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # triggers only on version tags like v1.0.0, v2.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from tag
      id: vars
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest \
                     -t ghcr.io/${{ github.repository }}:${{ env.VERSION }} .

    - name: Push Docker images
      run: |
        docker push ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:${{ env.VERSION }}
